apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cda-ws
  name: cda-ws
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cda-ws
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cda-ws
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
