apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cda
  name: cda
spec:
  containers:
  - image: nginx
    name: cda
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}